In [32]:
import torch
a = torch.tensor(list(range(9))) 
a.size()


torch.Size([9])

In [33]:
a.storage_offset() 

0

In [34]:
a.stride() 

(1,)

In [35]:
b = a.view(3, 3)
b 

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [20]:
a.storage().data_ptr() == b.storage().data_ptr() 

True

In [17]:
a.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]

In [21]:
b.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]

In [22]:
c = torch.tensor(b[1:, 1:])
c 

/tmp/ipykernel_666/3781880054.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  c = torch.tensor(b[1:, 1:])


tensor([[4, 5],
        [7, 8]])

In [24]:
c.size()

torch.Size([2, 2])

In [26]:
c.storage_offset() 

0

In [27]:
c.stride()

(2, 1)

In [28]:
torch.sqrt(torch.tensor([1.0, 4.0, 9.0])) # square root 

tensor([1., 2., 3.])

In [31]:
d = torch.tensor([1.0, 4.0, 9.0])
d.sqrt_()

tensor([1., 2., 3.])

In [36]:
a.sqrt_() # need to be float 

RuntimeError: result type Float can't be cast to the desired output type Long

In [37]:
a = torch.tensor(list(range(9)))
a.cos_() 

RuntimeError: result type Float can't be cast to the desired output type Long

In [38]:
a = a.float()
a.sqrt() 

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])